### ISSUE TITLE
Permission denied while trying to create user html files

### ISSUE THREAD

**Issue by vermontdevil** [dsp444/save_canvas_discussion#1]
Hi - this is a fabulous script! But I'm having an issue. I was able to get the JSON data but I am getting a permission denied when the script tries to create the html file for each of the user.

Here's the error message:

Traceback (most recent call last):
  File "canvas.py", line 177, in <module>
    get_discussion_posts( sys.argv[1] )
  File "canvas.py", line 126, in get_discussion_posts
    write_post_to_file( os.path.dirname( fname ), name, id, post['message'], post['updated_at'], os.path.basename( fname
 ).split('.')[0] )
  File "canvas.py", line 68, in write_post_to_file
    with open( fname, 'w' ) as file:
PermissionError: [Errno 13] Permission denied: '/xxx_xxxxx.html'

I tried this on Mac and Windows and was not able to figure out why. I ran another python script that outputted to a file and had no issues.

Any insight?

Thanks

**Comment by dsp444** [comment]
Hi vermontdevil,
Sorry for the super-slow reply...I posted this and then essentially ignored it because I don't use Githib all that often.  It appears that the problem is that the script is trying to write to the '/' path, the root directory, which would be not allowed on most systems.  It turns out whenever I ran it, I included the path to the .json file every time, which didn't cause the problem you saw.

I fixed the problem and uploaded the fixed version.  Thank you for pointing out the problem.
